"""baseline

Revision ID: 4e2ca29cbb85
Revises:
Create Date: 2025-06-17 19:39:51.104023

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4e2ca29cbb85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
