"""Add progress and status_message to Package model

Revision ID: 8be520464bbd
Revises: 9578103e1453
Create Date: 2025-06-20 12:25:37.305739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be520464bbd'
down_revision = '9578103e1453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status_message', sa.String(length=255), nullable=True))
        batch_op.alter_column('package_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('status_message')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
