"""add_package_status_and_uuid

Revision ID: 9578103e1453
Revises: a88fb8c437c9
Create Date: 2025-06-19 11:28:38.214647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9578103e1453'
down_revision = 'a88fb8c437c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='statusenum'), nullable=False))
        batch_op.add_column(sa.Column('stage', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("uq_packages_package_id", ['package_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stage')
        batch_op.drop_column('status')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
