"""Add Package table

Revision ID: a88fb8c437c9
Revises: 4e2ca29cbb85
Create Date: 2025-06-17 21:00:59.425793

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a88fb8c437c9"
down_revision = "4e2ca29cbb85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("installer_path", sa.String(length=500), nullable=True),
        sa.Column("script_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packages")
    # ### end Alembic commands ###
